name: Main_Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
        
      # This Lints the Code for Style Errors (Uses GitHub's Super Linter)
      - name: Begin the Linting
        lint:
          - name: Run Super-Linter
            uses: github/super-linter@v3
              env:
                DEFAULT_BRANCH: main
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
      # Extra Space to add more Tests
     # - name: new test
     # job:
